parameters: {}
secrets:
  pg_server:
    pg_server_password: ""
  api:
    ConnectionStrings__shows: ""
    pg_server_password: ""
    SHOWS_URI: ""
config:
  pg_server:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  api:
    SHOWS_HOST: "pg-server-service"
    SHOWS_PORT: "5432"
    SHOWS_USERNAME: "postgres"
    SHOWS_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg-server-service:5432/shows"
    SHOWS_DATABASENAME: "shows"
  gateway:
    ASPNETCORE_ENVIRONMENT: "Production"
    FRONTEND_HTTP: "http://frontend-service:80"
    REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/{**catchall}"
    REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_frontend"
    REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/api/{**catchall}"
    REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_api"
    REVERSEPROXY__CLUSTERS__cluster_frontend__DESTINATIONS__destination1__ADDRESS: "http://frontend"
    REVERSEPROXY__CLUSTERS__cluster_api__DESTINATIONS__destination1__ADDRESS: "http://api"
    services__frontend__http__0: "http://frontend-service:80"
    API_HTTP: "http://api-service:8080"
    services__api__http__0: "http://api-service:8080"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://shows-k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "gateway"
