---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "pg-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "pg"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.pg.pg_password }}"
type: "Opaque"
