---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  SHOWS_HOST: "{{ .Values.config.api.SHOWS_HOST }}"
  SHOWS_PORT: "{{ .Values.config.api.SHOWS_PORT }}"
  SHOWS_USERNAME: "{{ .Values.config.api.SHOWS_USERNAME }}"
  SHOWS_JDBCCONNECTIONSTRING: "{{ .Values.config.api.SHOWS_JDBCCONNECTIONSTRING }}"
  SHOWS_DATABASENAME: "{{ .Values.config.api.SHOWS_DATABASENAME }}"
