---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__shows: "Host=pg-server-service;Port=5432;Username=postgres;Password={{ .Values.secrets.api.pg_server_password }};Database=shows"
  SHOWS_PASSWORD: "{{ .Values.secrets.api.pg_server_password }}"
  SHOWS_URI: "postgresql://postgres:{{ .Values.secrets.api.pg_server_password }}@pg-server-service:5432/shows"
type: "Opaque"
